### ISSUE TITLE
Can't delete default mining pools via GUI 

### ISSUE THREAD

**Issue by pingram3541** [bcndev/bytecoin-gui#2]
Tried both MAC and Linux binary versions and neither will allow you to delete the default mining nodes from the GUI.  Clicking the delete X's has no response.

I did find that you can delete them from the .cfg file however.

**Comment by bcndev** [comment]
@pingram3541 We'll also tackle this issue pretty soon.

**Comment by bcndev** [comment]
Fixed in fc372ccfcc9c4505d3cd7857c30632a05bda54a8.
