### ISSUE TITLE
Can't re-order mining pools

### ISSUE THREAD

**Issue by pingram3541** [bcndev/bytecoin-gui#3]
Both MAC and Linux binaries, when you click and drag to re-order a pool in the mining tab as soon as you let go of mouse to release the pool's position in order, the app crashes and completely disappears.

**Comment by bcndev** [comment]
@pingram3541 Thanks for your report. We are aware of this problem and will surely fix it during stabilization period.

**Comment by bcndev** [comment]
Fixed in fc372ccfcc9c4505d3cd7857c30632a05bda54a8.
